from django.conf.urls.defaults import patterns
from django.views.generic.simple import direct_to_template

from jolly.http import MethodDispatcher
from jolly.view import (root, get, get_many, 
	                delete_command, put_command, post_command,
			delete_breakpoint, post_breakpoint)

urlpatterns = patterns('',
    (r'^$', MethodDispatcher({'GET': root})),
    (r'^g$', 
        MethodDispatcher({'GET': get_many}), 
        {'doc_type': 'jolly.core.Game'}, 
        'games'),
    (r'^g/(?P<doc_id>[0-9a-f]{32})$', 
        MethodDispatcher({'GET': get}), 
        {'doc_type': 'jolly.core.Game'}, 
        'game'),
    (r'^map/(?P<doc_id>[0-9a-f]{32})$', 
        MethodDispatcher({'GET': get}), 
        {'doc_type': 'jolly.map.Map'}, 
        'map'),
    (r'^player$', 
        MethodDispatcher({'GET': get_many}), 
        {'doc_type': 'jolly.core.Player', 'query': ['g', 'user']}, 
        'players'),
    (r'^player/(?P<doc_id>[0-9a-f]{32})$', 
        MethodDispatcher({'GET': get}), 
        {'doc_type': 'jolly.core.Player'}, 
        'player'),
    (r'^unit/(?P<doc_id>[0-9a-f]{32})$', 
        MethodDispatcher({'GET': get}), 
        {'doc_type': 'jolly.system.System'}, 
        'unit'),
    (r'^system/(?P<doc_id>[0-9a-f]{32})$', 
        MethodDispatcher({'GET': get}), 
        {'doc_type': 'jolly.system.System'}, 
        'system'),
    (r'^user$', 
        MethodDispatcher({'GET': get_many}), 
        {'doc_type': 'jolly.core.User'}, 
        'users'),
    (r'^user/(?P<doc_id>[0-9a-f]{32})$', 
        MethodDispatcher({'GET': get}), 
        {'doc_type': 'jolly.core.User'}, 
        'user'),
    (r'^queue/(?P<doc_id>[0-9a-f]{32})$', 
        MethodDispatcher({'GET': get,
	                  'POST': post_command}), 
        {'doc_type': 'jolly.command.CommandQueue', 'private_view': True}, 
        'command-queue'),
    (r'^command/(?P<doc_id>[0-9a-f]{32})$', 
        MethodDispatcher({'GET': get, 
                          'DELETE': delete_command,
                          'PUT': put_command}), 
        {'doc_type': 'jolly.command.Command', 'private_view': True}, 
        'command'),
    (r'^log/(?P<doc_id>[0-9a-f]{32})$', 
    MethodDispatcher({'GET': get}), 
        {'doc_type': 'jolly.core.ActionLog', 'private_view': True}, 
        'log'),
    (r'^gamelog/(?P<doc_id>[0-9a-f]{32})$', 
    MethodDispatcher({'GET': get}), 
        {'doc_type': 'jolly.core.ActionLog', 'private_view': False}, 
        'gamelog'),
    (r'^status/(?P<doc_id>[0-9a-f]{32})$', 
        MethodDispatcher({'GET': get}), 
        {'doc_type': 'jolly.core.Status', 'private_view': True}, 
        'status'),
    (r'^breakpoint$', 
        MethodDispatcher({'GET': get_many,
	                  'POST': post_breakpoint}), 
	{'doc_type': 'jolly.breakpoint.BreakPoint', 
	 'query': ['player'], 
	 'private_view': True}, 
        'breakpoints'),
    (r'^breakpoint/(?P<doc_id>[0-9a-f]{32})$', 
        MethodDispatcher({'GET': get,
	                  'DELETE': delete_breakpoint}), 
	{'doc_type': 'jolly.breakpoint.BreakPoint', 'private_view': True}, 
        'breakpoint'),
#    (r'^scenario/(?P<doc_id>[0-9a-f]{32})$', 
#        MethodDispatcher({'GET': get}), 
#        {'doc_type': 'jolly.core.Scenario'}, 
#        'scenario'),
    (r'^command-template/(?P<name>[a-zA-Z-]+)$',
        MethodDispatcher({'GET': direct_to_template}),
        {'doc_type': 'jolly.command.CommandTemplate',
         'template': ''},
	'command-template'),
    (r'^test/test_ajax.html', 
        direct_to_template, 
        {'template': 'test_ajax.html'}),
    (r'^test/test_window.html', 
        direct_to_template, 
        {'template': 'test_window.html'}),
    (r'^test/test_map.html', 
        direct_to_template, 
        {'template': 'test_map.html'}),
    (r'^window.js', 
        direct_to_template, 
        {'template': 'window.js'}),
    (r'^map.js', 
        direct_to_template, 
        {'template': 'map.js'}),
)


